# generated by datamodel-codegen:
#   filename:  <stdin>

from __future__ import annotations

from datetime import date

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class Package(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    clear_name: str = Field(..., alias="clearName")
    package_id: int = Field(..., alias="packageId")
    field__typename: str = Field(..., alias="__typename")


class FlatrateItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    package: Package
    field__typename: str = Field(..., alias="__typename")


class BuyItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    package: Package
    field__typename: str = Field(..., alias="__typename")


class FreeItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    package: Package
    field__typename: str = Field(..., alias="__typename")


class FastItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    package: Package
    field__typename: str = Field(..., alias="__typename")


class PlanOffer(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    retail_price: str | None = Field(..., alias="retailPrice")
    duration_days: int = Field(..., alias="durationDays")
    presentation_type: str = Field(..., alias="presentationType")
    is_trial: bool = Field(..., alias="isTrial")
    retail_price_value: float | None = Field(..., alias="retailPriceValue")
    currency: str
    field__typename: str = Field(..., alias="__typename")


class Package4(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    package_id: int = Field(..., alias="packageId")
    short_name: str = Field(..., alias="shortName")
    clear_name: str = Field(..., alias="clearName")
    monetization_types: list[str] = Field(..., alias="monetizationTypes")
    icon: str
    icon_wide: str = Field(..., alias="iconWide")
    has_rectangular_icon: bool = Field(..., alias="hasRectangularIcon")
    plan_offers: list[PlanOffer] = Field(..., alias="planOffers")
    field__typename: str = Field(..., alias="__typename")


class UpcomingRelease(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    release_count_down: int = Field(..., alias="releaseCountDown")
    release_date: date = Field(..., alias="releaseDate")
    release_type: str = Field(..., alias="releaseType")
    label: str
    package: Package4 | None
    field__typename: str = Field(..., alias="__typename")


class Content(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    field__typename: str = Field(..., alias="__typename")
    title: str
    short_description: str = Field(..., alias="shortDescription")
    episode_number: int = Field(..., alias="episodeNumber")
    season_number: int = Field(..., alias="seasonNumber")
    is_released: bool = Field(..., alias="isReleased")
    runtime: int
    upcoming_releases: list[UpcomingRelease] = Field(..., alias="upcomingReleases")
    original_release_date: date | None = Field(None, alias="originalReleaseDate")


class Episode(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    object_id: int = Field(..., alias="objectId")
    object_type: str = Field(..., alias="objectType")
    seenlist_entry: None = Field(..., alias="seenlistEntry")
    unique_offer_count: int = Field(..., alias="uniqueOfferCount")
    flatrate: list[FlatrateItem]
    buy: list[BuyItem]
    rent: list[None]
    free: list[FreeItem]
    fast: list[FastItem]
    content: Content
    field__typename: str = Field(..., alias="__typename")
    offer_count: int | None = Field(None, alias="offerCount")
    max_offer_updated_at: AwareDatetime | None = Field(None, alias="maxOfferUpdatedAt")


class Node(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    field__typename: str = Field(..., alias="__typename")
    episodes: list[Episode]


class Data(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    node: Node


class CustomSeasonEpisodesResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: Data
