# generated by datamodel-codegen:
#   filename:  <dict>

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class Variables(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    full_path: str = Field(..., alias="fullPath")
    language: str
    country: str


class TitleDetailArticle(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    operation_name: str = Field(..., alias="operationName")
    variables: Variables
    query: str
