# generated by datamodel-codegen:
#   filename:  <stdin>

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class Variables(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    platform: str
    country: str
    language: str
    limit: int
    node_id: str = Field(..., alias="nodeId")
    offset: int


class SeasonEpisodesRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    operation_name: str = Field(..., alias="operationName")
    variables: Variables
    query: str
