# TODO: Validate
from __future__ import annotations

from typing import TYPE_CHECKING

import pytest

from just_scrape.exceptions import InvalidFileError
from tests.utils import assert_error, download_and_save, load_ids, parsed_json

if TYPE_CHECKING:
    from just_scrape import JustScrape
    from just_scrape.buy_box_offers import BuyBoxOffers

INVALID_NODE_ID = "tse9999999"
"""The API answers an unknown node_id with an empty stub node instead of an
error, so the endpoint raises for it itself."""

NODE_IDS = load_ids("buy_box_offers")
"""Generated by ``tests.update_ids``; add new ids through that tool."""


@pytest.fixture(scope="session")
def endpoint(client: JustScrape) -> BuyBoxOffers:
    return client.buy_box_offers


@pytest.fixture(params=NODE_IDS)
def node_id(request: pytest.FixtureRequest) -> str:
    return request.param


class TestBuyBoxOffers:
    def test_download(self, endpoint: BuyBoxOffers, node_id: str) -> None:
        download_and_save(
            endpoint,
            node_id,
            lambda: endpoint.download(node_id),
        )

    def test_parse(self, endpoint: BuyBoxOffers, node_id: str) -> None:
        data = parsed_json(endpoint, node_id)
        assert data.data.node.id == node_id

    def test_invalid_download(self, endpoint: BuyBoxOffers) -> None:
        assert_error(
            endpoint,
            INVALID_NODE_ID,
            lambda: endpoint.download(INVALID_NODE_ID),
            InvalidFileError,
        )
