# TODO: Validate
from __future__ import annotations

from typing import TYPE_CHECKING

import pytest

from just_scrape.exceptions import GraphQLError
from tests.utils import (
    assert_error,
    download_and_save,
    load_ids,
    parsed_json,
    path_name,
)

if TYPE_CHECKING:
    from just_scrape import JustScrape
    from just_scrape.title_detail_article import TitleDetailArticle

INVALID_MOVIE_PATH = "/us/movie/invalid-movie"

PATHS = load_ids("title_detail_article")
"""Generated by ``tests.update_ids``; add new ids through that tool."""


@pytest.fixture(scope="session")
def endpoint(client: JustScrape) -> TitleDetailArticle:
    return client.title_detail_article


@pytest.fixture(params=PATHS)
def full_path(request: pytest.FixtureRequest) -> str:
    return request.param


class TestTitleDetailArticle:
    def test_download(self, endpoint: TitleDetailArticle, full_path: str) -> None:
        download_and_save(
            endpoint,
            path_name(full_path),
            lambda: endpoint.download(full_path),
        )

    def test_parse(self, endpoint: TitleDetailArticle, full_path: str) -> None:
        data = parsed_json(endpoint, path_name(full_path))
        assert data is not None

    def test_invalid_download(self, endpoint: TitleDetailArticle) -> None:
        assert_error(
            endpoint,
            path_name(INVALID_MOVIE_PATH),
            lambda: endpoint.download(INVALID_MOVIE_PATH),
            GraphQLError,
        )
