# TODO: Validate
from __future__ import annotations

from typing import TYPE_CHECKING

import pytest

from just_scrape.exceptions import GraphQLError
from tests.utils import (
    assert_error,
    download_and_save,
    load_ids,
    parsed_json,
    path_name,
)

if TYPE_CHECKING:
    from just_scrape import JustScrape
    from just_scrape.url_title_details import UrlTitleDetails

INVALID_URL_PATH = "/us/tv-show/invalid-url"

PATHS = load_ids("url_title_details")
"""Generated by ``tests.update_ids``; add new ids through that tool."""


@pytest.fixture(scope="session")
def endpoint(client: JustScrape) -> UrlTitleDetails:
    return client.url_title_details


class TestUrlTitleDetails:
    @pytest.mark.parametrize("full_path", PATHS)
    def test_download(self, endpoint: UrlTitleDetails, full_path: str) -> None:
        download_and_save(
            endpoint,
            path_name(full_path),
            lambda: endpoint.download(full_path),
        )

    @pytest.mark.parametrize("full_path", PATHS)
    def test_parse(self, endpoint: UrlTitleDetails, full_path: str) -> None:
        data = parsed_json(endpoint, path_name(full_path))
        assert data.data.url_v2.node.content.full_path == full_path

    def test_invalid_download(self, endpoint: UrlTitleDetails) -> None:
        assert_error(
            endpoint,
            path_name(INVALID_URL_PATH),
            lambda: endpoint.download(INVALID_URL_PATH),
            GraphQLError,
        )
