# ruff: noqa: ERA001
# generated by datamodel-codegen:
#   filename:  temp.json

from __future__ import annotations

from pydantic import BaseModel, Field


class Variables(BaseModel):
    platform: str
    fallback_to_foreign_offers: bool = Field(..., alias="fallbackToForeignOffers")
    exclude_packages: list[str] = Field(..., alias="excludePackages")
    node_id: str = Field(..., alias="nodeId")
    country: str
    language: str


class ModelItem(BaseModel):
    operation_name: str = Field(..., alias="operationName")
    variables: Variables
    query: str
