# generated by datamodel-codegen:
#   filename:  <dict>

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class Content1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    field__typename: str = Field(..., alias="__typename")
    synopsis: str
    what_to_know: None = Field(..., alias="whatToKnow")
    production_news: None = Field(..., alias="productionNews")


class Article(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    content: Content1
    field__typename: str = Field(..., alias="__typename")


class Content(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    articles: list[Article]
    field__typename: str = Field(..., alias="__typename")


class Node(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    content: Content
    field__typename: str = Field(..., alias="__typename")


class UrlV2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    node: Node
    field__typename: str = Field(..., alias="__typename")


class Data(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    url_v2: UrlV2 = Field(..., alias="urlV2")


class Model(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: Data
