# generated by datamodel-codegen:
#   filename:  <dict>

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class Variables(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    platform: str
    fallback_to_foreign_offers: bool = Field(..., alias="fallbackToForeignOffers")
    exclude_packages: list[str] = Field(..., alias="excludePackages")
    node_id: str = Field(..., alias="nodeId")
    country: str
    language: str


class ModelItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    operation_name: str = Field(..., alias="operationName")
    variables: Variables
    query: str
