# ruff: noqa: ERA001
# generated by datamodel-codegen:
#   filename:  temp.json

from __future__ import annotations

from pydantic import BaseModel, Field


class Content1(BaseModel):
    field__typename: str = Field(..., alias="__typename")
    synopsis: str
    what_to_know: None = Field(..., alias="whatToKnow")
    production_news: None = Field(..., alias="productionNews")


class Article(BaseModel):
    id: str
    content: Content1
    field__typename: str = Field(..., alias="__typename")


class Content(BaseModel):
    articles: list[Article]
    field__typename: str = Field(..., alias="__typename")


class Node(BaseModel):
    id: str
    content: Content
    field__typename: str = Field(..., alias="__typename")


class UrlV2(BaseModel):
    id: str
    node: Node
    field__typename: str = Field(..., alias="__typename")


class Data(BaseModel):
    url_v2: UrlV2 = Field(..., alias="urlV2")


class ModelItem(BaseModel):
    data: Data
