# ruff: noqa: ERA001
# generated by datamodel-codegen:
#   filename:  temp.json
from pydantic import BaseModel, ConfigDict, Field


class Variables(BaseModel):
    ConfigDict(extra="forbid")
    full_path: str = Field(..., alias="fullPath")
    language: str
    country: str


class ModelItem(BaseModel):
    ConfigDict(extra="forbid")
    operation_name: str = Field(..., alias="operationName")
    variables: Variables
    query: str
