# ruff: noqa: ERA001
# generated by datamodel-codegen:
#   filename:  temp.json

from __future__ import annotations

from pydantic import BaseModel, Field


class Variables(BaseModel):
    full_path: str = Field(..., alias="fullPath")
    language: str
    country: str


class ModelItem(BaseModel):
    operation_name: str = Field(..., alias="operationName")
    variables: Variables
    query: str
