# generated by datamodel-codegen:
#   filename:  <stdin>

from __future__ import annotations

from datetime import date as date_aliased

from pydantic import BaseModel, ConfigDict, Field


class Filter(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    age_certifications: list[None] = Field(..., alias="ageCertifications")
    exclude_genres: list[None] = Field(..., alias="excludeGenres")
    exclude_production_countries: list[None] = Field(
        ...,
        alias="excludeProductionCountries",
    )
    object_types: list[None] = Field(..., alias="objectTypes")
    production_countries: list[None] = Field(..., alias="productionCountries")
    subgenres: list[None]
    genres: list[None]
    packages: list[str]
    exclude_irrelevant_titles: bool = Field(..., alias="excludeIrrelevantTitles")
    presentation_types: list[None] = Field(..., alias="presentationTypes")
    monetization_types: list[None] = Field(..., alias="monetizationTypes")


class Variables(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    first: int
    page_type: str = Field(..., alias="pageType")
    date: date_aliased
    filter: Filter
    language: str
    country: str
    price_drops: bool = Field(..., alias="priceDrops")
    platform: str
    show_date_badge: bool = Field(..., alias="showDateBadge")
    available_to_packages: list[str] = Field(..., alias="availableToPackages")
    after: str | None = None


class NewTitles(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    operation_name: str = Field(..., alias="operationName")
    variables: Variables
    query: str
