# generated by datamodel-codegen:
#   filename:  <stdin>

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class NewTitlesFilter(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    age_certifications: list[None] = Field(..., alias="ageCertifications")
    exclude_genres: list[None] = Field(..., alias="excludeGenres")
    exclude_production_countries: list[None] = Field(
        ...,
        alias="excludeProductionCountries",
    )
    object_types: list[None] = Field(..., alias="objectTypes")
    production_countries: list[None] = Field(..., alias="productionCountries")
    subgenres: list[None]
    genres: list[None]
    packages: list[None]
    exclude_irrelevant_titles: bool = Field(..., alias="excludeIrrelevantTitles")
    presentation_types: list[None] = Field(..., alias="presentationTypes")
    monetization_types: list[None] = Field(..., alias="monetizationTypes")


class Variables(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    first: int
    bucket_size: int = Field(..., alias="bucketSize")
    group_by: str = Field(..., alias="groupBy")
    page_type: str = Field(..., alias="pageType")
    country: str
    new_after_cursor: str = Field(..., alias="newAfterCursor")
    new_titles_filter: NewTitlesFilter = Field(..., alias="newTitlesFilter")
    price_drops: bool = Field(..., alias="priceDrops")


class NewTitleBuckets(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    operation_name: str = Field(..., alias="operationName")
    variables: Variables
    query: str
