# ruff: noqa: ERA001
# generated by datamodel-codegen:
#   filename:  temp.json
from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class Variables(BaseModel):
    ConfigDict(extra="forbid")
    platform: str
    country: str
    language: str
    limit: int
    node_id: str = Field(..., alias="nodeId")
    offset: int


class ModelItem(BaseModel):
    ConfigDict(extra="forbid")
    operation_name: str = Field(..., alias="operationName")
    variables: Variables
    query: str
