# generated by datamodel-codegen:
#   filename:  <stdin>

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class Content(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    articles: list[None]
    field__typename: str = Field(..., alias="__typename")


class Node(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    content: Content
    field__typename: str = Field(..., alias="__typename")


class UrlV2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    node: Node
    field__typename: str = Field(..., alias="__typename")


class Data(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    url_v2: UrlV2 = Field(..., alias="urlV2")


class TitleDetailArticleResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: Data
