"""UrlTitleDetailsModel, strict to a type checker, all-optional at runtime.

A type checker reads the strict model, so every field carries the type and
the requiredness the schema recorded. At runtime the all-optional copy is imported
instead, so a response that has drifted still parses and a field the data is
missing is None despite what its type hint says.
"""

from typing import TYPE_CHECKING

from good_ass_pydantic_integrator import load

from .optional_models import UrlTitleDetailsModel as OptionalModel
from .strict_models import UrlTitleDetailsModel as StrictModel

if TYPE_CHECKING:
    from .strict_models import (
        Backdrop,
        Clip,
        Content,
        Content1,
        Content2,
        Content3,
        Content4,
        Content5,
        Content6,
        Content7,
        Credit,
        DailymotionClip,
        Data,
        DateRange,
        Edge,
        ExternalIds,
        FallBackClips,
        FallBackClips1,
        FlatrateItem,
        FullBackdrop,
        Genre,
        Genre1,
        Interactions,
        Interactions1,
        Node,
        Node1,
        Offer,
        OffersHistoryItem,
        Package,
        Package1,
        Package2,
        Package3,
        Plan,
        PlanOffer,
        PopularityRank,
        RankInfo,
        RecentEpisode,
        Scoring,
        Scoring1,
        Season,
        SeenState,
        Show,
        Show1,
        SimilarTitlesV2,
        StreamingChartInfo,
        StreamingCharts,
        Subgenre,
        Tag,
        Template,
        Title,
        TitleModules,
        Titles1Item,
        Url,
        UrlTitleDetailsModel,
        UrlV2,
        WatchNowOffer,
    )
else:
    from .optional_models import (
        Backdrop,
        Clip,
        Content,
        Content1,
        Content2,
        Content3,
        Content4,
        Content5,
        Content6,
        Content7,
        Credit,
        DailymotionClip,
        Data,
        DateRange,
        Edge,
        ExternalIds,
        FallBackClips,
        FallBackClips1,
        FlatrateItem,
        FullBackdrop,
        Genre,
        Genre1,
        Interactions,
        Interactions1,
        Node,
        Node1,
        Offer,
        OffersHistoryItem,
        Package,
        Package1,
        Package2,
        Package3,
        Plan,
        PlanOffer,
        PopularityRank,
        RankInfo,
        RecentEpisode,
        Scoring,
        Scoring1,
        Season,
        SeenState,
        Show,
        Show1,
        SimilarTitlesV2,
        StreamingChartInfo,
        StreamingCharts,
        Subgenre,
        Tag,
        Template,
        Title,
        TitleModules,
        Titles1Item,
        Url,
        UrlTitleDetailsModel,
        UrlV2,
        WatchNowOffer,
    )

__all__ = [
    "Backdrop",
    "Clip",
    "Content",
    "Content1",
    "Content2",
    "Content3",
    "Content4",
    "Content5",
    "Content6",
    "Content7",
    "Credit",
    "DailymotionClip",
    "Data",
    "DateRange",
    "Edge",
    "ExternalIds",
    "FallBackClips",
    "FallBackClips1",
    "FlatrateItem",
    "FullBackdrop",
    "Genre",
    "Genre1",
    "Interactions",
    "Interactions1",
    "Node",
    "Node1",
    "Offer",
    "OffersHistoryItem",
    "Package",
    "Package1",
    "Package2",
    "Package3",
    "Plan",
    "PlanOffer",
    "PopularityRank",
    "RankInfo",
    "RecentEpisode",
    "Scoring",
    "Scoring1",
    "Season",
    "SeenState",
    "Show",
    "Show1",
    "SimilarTitlesV2",
    "StreamingChartInfo",
    "StreamingCharts",
    "Subgenre",
    "Tag",
    "Template",
    "Title",
    "TitleModules",
    "Titles1Item",
    "Url",
    "UrlTitleDetailsModel",
    "UrlV2",
    "WatchNowOffer",
    "model_validate_json",
]


def model_validate_json(data: str | bytes | object, log_id: str) -> UrlTitleDetailsModel:
    """Read a downloaded file into UrlTitleDetailsModel."""
    return load.model_validate_json(StrictModel, OptionalModel, data, log_id)
